/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacegui;

/**
 *
 * @author Suporte
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmnbMenuPrincipal = new javax.swing.JMenuBar();
        jmnuCadastro = new javax.swing.JMenu();
        jimnuCadastroProdutos = new javax.swing.JMenuItem();
        jimnuCadastroClientes = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jimnuSair = new javax.swing.JMenuItem();
        jmnuPesquisar = new javax.swing.JMenu();
        jimnuPesquisarProdutos = new javax.swing.JMenuItem();
        jimnuPesquisarClientes = new javax.swing.JMenuItem();
        jmnuSobre = new javax.swing.JMenu();
        jimnuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trabalho");

        jmnuCadastro.setText("Cadastro");

        jimnuCadastroProdutos.setText("Cadastro Produtos");
        jimnuCadastroProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jimnuCadastroProdutosActionPerformed(evt);
            }
        });
        jmnuCadastro.add(jimnuCadastroProdutos);

        jimnuCadastroClientes.setText("Cadstro de Clientes");
        jimnuCadastroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jimnuCadastroClientesActionPerformed(evt);
            }
        });
        jmnuCadastro.add(jimnuCadastroClientes);
        jmnuCadastro.add(jSeparator1);

        jimnuSair.setText("Sair");
        jimnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jimnuSairActionPerformed(evt);
            }
        });
        jmnuCadastro.add(jimnuSair);

        jmnbMenuPrincipal.add(jmnuCadastro);

        jmnuPesquisar.setText("Pesquisar");

        jimnuPesquisarProdutos.setText("Pesquisar Produtos");
        jimnuPesquisarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jimnuPesquisarProdutosActionPerformed(evt);
            }
        });
        jmnuPesquisar.add(jimnuPesquisarProdutos);

        jimnuPesquisarClientes.setText("Pesquisar Clientes");
        jimnuPesquisarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jimnuPesquisarClientesActionPerformed(evt);
            }
        });
        jmnuPesquisar.add(jimnuPesquisarClientes);

        jmnbMenuPrincipal.add(jmnuPesquisar);

        jmnuSobre.setText("Sobre");

        jimnuSobre.setText("Sobre");
        jimnuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jimnuSobreActionPerformed(evt);
            }
        });
        jmnuSobre.add(jimnuSobre);

        jmnbMenuPrincipal.add(jmnuSobre);

        setJMenuBar(jmnbMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jimnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jimnuSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jimnuSairActionPerformed

    private void jimnuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jimnuSobreActionPerformed
        JanelaSobre janelaSobre = new JanelaSobre(this, true);
        janelaSobre.setVisible(true);
    }//GEN-LAST:event_jimnuSobreActionPerformed

    private void jimnuPesquisarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jimnuPesquisarClientesActionPerformed
        JanelaPesquisaClientes janelaPesquisaClientes = new JanelaPesquisaClientes(this, true);
        janelaPesquisaClientes.setVisible(true);
    }//GEN-LAST:event_jimnuPesquisarClientesActionPerformed

    private void jimnuCadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jimnuCadastroClientesActionPerformed
        janelaCadastroCliente janeCadastroCliente = new janelaCadastroCliente(this, true);
        janeCadastroCliente.setVisible(true);
    }//GEN-LAST:event_jimnuCadastroClientesActionPerformed

    private void jimnuCadastroProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jimnuCadastroProdutosActionPerformed
        janelaCadastroProduto jaCadastroProduto = new janelaCadastroProduto(this, true);
        jaCadastroProduto.setVisible(true);
    }//GEN-LAST:event_jimnuCadastroProdutosActionPerformed

    private void jimnuPesquisarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jimnuPesquisarProdutosActionPerformed
        JanelaPesquisaProdutos janelaPesquisaProdutos = new JanelaPesquisaProdutos(this, true);
        janelaPesquisaProdutos.setVisible(true);
    }//GEN-LAST:event_jimnuPesquisarProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem jimnuCadastroClientes;
    private javax.swing.JMenuItem jimnuCadastroProdutos;
    private javax.swing.JMenuItem jimnuPesquisarClientes;
    private javax.swing.JMenuItem jimnuPesquisarProdutos;
    private javax.swing.JMenuItem jimnuSair;
    private javax.swing.JMenuItem jimnuSobre;
    private javax.swing.JMenuBar jmnbMenuPrincipal;
    private javax.swing.JMenu jmnuCadastro;
    private javax.swing.JMenu jmnuPesquisar;
    private javax.swing.JMenu jmnuSobre;
    // End of variables declaration//GEN-END:variables
}
