/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacegui;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import persistencia.PersistirCliente;

/**
 *
 * @author Suporte
 */
public class JanelaPesquisaClientes extends javax.swing.JDialog {

    private PersistirCliente persistirCliente = new PersistirCliente();
    private DefaultTableModel modelo;

    /**
     * Creates new form JanelaPesquisaClientes
     */
    public JanelaPesquisaClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        modelo = (DefaultTableModel) jtblCliente.getModel();
        preencherTabela(persistirCliente.lerClientes());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblCliente = new javax.swing.JTable();
        jbtnExcluir = new javax.swing.JButton();
        jbtnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jtblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Rua", "Bairro", "Telefone", "Cidade", "Número"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblCliente);

        jbtnExcluir.setText("Excluir");
        jbtnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnExcluirMouseClicked(evt);
            }
        });

        jbtnEditar.setText("Editar");
        jbtnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnEditarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jbtnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnExcluir)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnExcluir)
                    .addComponent(jbtnEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnExcluirMouseClicked
        if (jtblCliente.getSelectedRow() == -1) {
            return;
        }
        this.modelo.removeRow(jtblCliente.getSelectedRow());

        String update = "";
        for (int i = 0; i < modelo.getRowCount(); i++) {
            for (int j = 0; j < persistirCliente.NUM_COLUMNS; j++) {
                update += (String) modelo.getValueAt(i, j);
                if ((j == (persistirCliente.NUM_COLUMNS - 1))
                        && (i < (modelo.getRowCount() - 1))) {
                    update += "\n";
                } else {
                    update += ";";
                }
            }
        }
        persistirCliente.atualizarClientes(update);
    }//GEN-LAST:event_jbtnExcluirMouseClicked

    private void jbtnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnEditarMouseClicked
        if (jtblCliente.getSelectedRow() == -1) {
            return;
        }

        janelaEdicaoCliente janelaEdicaoCliente = new janelaEdicaoCliente(null, true, this);

        janelaEdicaoCliente.getJtxtNome().setText((String) modelo.getValueAt(jtblCliente.getSelectedRow(), 0));
        janelaEdicaoCliente.getJtxtRua().setText((String) modelo.getValueAt(jtblCliente.getSelectedRow(), 1));
        janelaEdicaoCliente.getJtxtBairro().setText((String) modelo.getValueAt(jtblCliente.getSelectedRow(), 2));
        String telefone = (String) modelo.getValueAt(jtblCliente.getSelectedRow(), 3);
        telefone = telefone.replace("(", "");
        telefone = telefone.replace(" ", "");
        telefone = telefone.replace(")", "");
        telefone = telefone.replace("-", "");
        janelaEdicaoCliente.getJftxtTelefone().setText(telefone);
        janelaEdicaoCliente.getJtxtCidade().setText((String) modelo.getValueAt(jtblCliente.getSelectedRow(), 4));
        janelaEdicaoCliente.getJtxtNumero().setText((String) modelo.getValueAt(jtblCliente.getSelectedRow(), 5));
        janelaEdicaoCliente.setVisible(true);

    }//GEN-LAST:event_jbtnEditarMouseClicked

    public void preencherTabela(Object[][] o) {
        if (o == null) {
            return;
        }

        for (int i = 0; i < o.length; i++) {
            this.modelo.addRow(o[i]);
        }
    }

    
    public JTable getJtblCliente() {
        return jtblCliente;
    }
    
    public PersistirCliente getPersistirCliente() {
        return persistirCliente;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPesquisaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPesquisaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPesquisaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPesquisaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JanelaPesquisaClientes dialog = new JanelaPesquisaClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnEditar;
    private javax.swing.JButton jbtnExcluir;
    private javax.swing.JTable jtblCliente;
    // End of variables declaration//GEN-END:variables
}
