/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacegui;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import persistencia.PersistirProduto;

/**
 *
 * @author Suporte
 */
public class janelaEdicaoProduto extends javax.swing.JDialog {

    private PersistirProduto persistirProduto;
    private JTable jtblCliente;
    private DefaultTableModel modelo;

    /**
     * Creates new form janelaCadastroCliente
     */
    public janelaEdicaoProduto(java.awt.Frame parent, boolean modal, JanelaPesquisaProdutos janelaPesquisa) {
        super(parent, modal);
        initComponents();
        jtblCliente = janelaPesquisa.getJtblProduto();
        modelo = (DefaultTableModel) jtblCliente.getModel();
        persistirProduto = janelaPesquisa.getPersistirProduto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnCancelar = new javax.swing.JButton();
        jbtnSalvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtxtDescricao = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnCancelarMouseClicked(evt);
            }
        });

        jbtnSalvar.setText("Salvar");
        jbtnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnSalvarMouseClicked(evt);
            }
        });

        jLabel1.setText("Dsc.:");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Edição de Produtos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtDescricao))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jbtnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnCancelar)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSalvar)
                    .addComponent(jbtnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCancelarMouseClicked
        this.dispose();
    }//GEN-LAST:event_jbtnCancelarMouseClicked

    private void jbtnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSalvarMouseClicked
        if (jtxtDescricao.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar!\n"
                    + "Existem campos não preenchidos.");
            return;
        }

        modelo.setValueAt(jtxtDescricao.getText(), jtblCliente.getSelectedRow(), 0);

        String update = "";
        for (int i = 0; i < modelo.getRowCount(); i++) {
            for (int j = 0; j < persistirProduto.NUM_COLUMNS; j++) {
                update += (String) modelo.getValueAt(i, j);
                if ((j == (persistirProduto.NUM_COLUMNS - 1))
                        && (i < (modelo.getRowCount() - 1))) {
                    update += "\n";
                } else {
                    update += ";";
                }
            }
        }
        persistirProduto.atualizarProdutos(update);
        this.dispose();
    }//GEN-LAST:event_jbtnSalvarMouseClicked

    
    /**
     * @return the jtxtNome
     */
    public javax.swing.JTextField getJtxtDescricao() {
        return jtxtDescricao;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnSalvar;
    private javax.swing.JTextField jtxtDescricao;
    // End of variables declaration//GEN-END:variables
}
